import java.awt.*;
import java.awt.datatransfer.*;
/*import javax.swing.event.*;*/
import java.awt.event.*;
import javax.swing.*;
import java.io.*;
import java.text.*;
import java.util.*;
import java.util.logging.*;
/** * * @author jatin kamboj */
public class ntpd extends javax.swing.JFrame {    
    /**     * Creates new form ntpd     */    
    Clipboard clip = getToolkit().getSystemClipboard();
    boolean textChanged=false;
    String holdText;
    String fn;
    String dir;
    String filename="";    
    boolean textchanged=false;
    static int fsize=17;
    Font font1;
    JList familylist, stylelist, sizelist;    
    String familyvalue[]={"Algerian"," Baskerville Old Face","Arial","Bauhaus 93","Blackadder ITC","Bookman Old Style","Castellar","Chiller","Magneto","Matura MT Script Capitals","Old English Text MT","Monotype Corsiva"};
    String sizevalue[]={"5","10","15","20","25","30","35","40","45","50","55","60","65","70"};
    int [] stylevalue={ Font.PLAIN, Font.BOLD, Font.ITALIC };
    String [] stylevalues={ "PLAIN", "BOLD", "ITALIC"};
    String ffamily, fsizestr, fstylestr;    
    int fstyle,cl,linecount,c2,lastIndex;       
    public ntpd() {    
        initComponents();
        init();    
        enabledisable();
        familylist = new JList(familyvalue);
	stylelist = new JList(stylevalues);
	sizelist = new JList(sizevalue);
        
        familylist.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
	sizelist.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
	stylelist.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);                     
    }                     
            
    public void init() {
        setLocationRelativeTo(null);           
    }     
    
    public void enabledisable(){
        int len = wrar.getText().length();
//        System.out.println(len);
        if(len == 0){
            saveitem.setEnabled(false);
            cpyitem.setEnabled(false);
            pstitem.setEnabled(false);
            ctitm.setEnabled(false);
            fnd.setEnabled(false);           
            saveasitem.setEnabled(false);
        }else{
            saveitem.setEnabled(true);
            cpyitem.setEnabled(true);
            pstitem.setEnabled(true);
            ctitm.setEnabled(true);;
            fnd.setEnabled(true);
            saveasitem.setEnabled(true);
        }
    }
    /**     * This method is called from within the constructor to initialize the form.     * WARNING: Do NOT modify this code. The content of this method is always     * regenerated by the Form Editor.     */    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        about = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        info = new javax.swing.JLabel();
        find = new javax.swing.JDialog();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        up = new javax.swing.JRadioButton();
        down = new javax.swing.JRadioButton();
        matchCase = new javax.swing.JCheckBox();
        jLabel8 = new javax.swing.JLabel();
        findWhat = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        buttonGroup1 = new javax.swing.ButtonGroup();
        bottom = new javax.swing.JPanel();
        details = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        wrar = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        file = new javax.swing.JMenu();
        newitem = new javax.swing.JMenuItem();
        openitem = new javax.swing.JMenuItem();
        saveitem = new javax.swing.JMenuItem();
        saveasitem = new javax.swing.JMenuItem();
        prntitem = new javax.swing.JMenuItem();
        exititem = new javax.swing.JMenuItem();
        delitem = new javax.swing.JMenuItem();
        edit = new javax.swing.JMenu();
        cpyitem = new javax.swing.JMenuItem();
        pstitem = new javax.swing.JMenuItem();
        ctitm = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        frmt = new javax.swing.JMenu();
        fntclr = new javax.swing.JMenuItem();
        bgclr = new javax.swing.JMenuItem();
        fntstyl = new javax.swing.JMenuItem();
        fntfmly = new javax.swing.JMenuItem();
        fntsz = new javax.swing.JMenuItem();
        fnd = new javax.swing.JMenuItem();
        view = new javax.swing.JMenu();
        stbr = new javax.swing.JRadioButtonMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();

        about.setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        about.setTitle("About JKNotepad");
        about.setIconImage(null);
        about.setMinimumSize(new java.awt.Dimension(550, 400));
        about.setPreferredSize(new java.awt.Dimension(550, 400));
        about.setResizable(false);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 51, 0), new java.awt.Color(255, 51, 51), new java.awt.Color(153, 153, 0), new java.awt.Color(255, 102, 102)), "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 11), new java.awt.Color(0, 204, 153))); // NOI18N
        jPanel1.setToolTipText("About Me");

        jLabel1.setFont(new java.awt.Font("Brush Script MT", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 0));
        jLabel1.setText("About");
        jLabel1.setToolTipText("About");

        jLabel2.setFont(new java.awt.Font("Brush Script MT", 3, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 0, 0));
        jLabel2.setText("JKNotepad 1.1.0");
        jLabel2.setToolTipText("JKNotepad");

        jLabel3.setFont(new java.awt.Font("Algerian", 3, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 0, 102));
        jLabel3.setText("This notepad has been created with the help");

        jLabel4.setFont(new java.awt.Font("Algerian", 3, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 0, 102));
        jLabel4.setText("of core java(awt and swing) by using");

        jLabel5.setFont(new java.awt.Font("Algerian", 3, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 0, 102));
        jLabel5.setText("java jdk 1.8.0_171");

        jLabel6.setFont(new java.awt.Font("Brush Script MT", 3, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 51, 0));
        jLabel6.setText("BY");

        jLabel7.setFont(new java.awt.Font("Brush Script MT", 3, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 51, 0));
        jLabel7.setText("Jatin Kumar");

        jButton1.setFont(new java.awt.Font("Centaur", 3, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(102, 51, 0));
        jButton1.setText("OK");
        jButton1.setToolTipText("ok");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        info.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/about.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(168, 168, 168)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(245, 245, 245)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGap(204, 204, 204)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGap(39, 39, 39)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 483, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(166, 166, 166)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(info, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(149, 149, 149)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(info))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jButton1))
                .addContainerGap(92, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout aboutLayout = new javax.swing.GroupLayout(about.getContentPane());
        about.getContentPane().setLayout(aboutLayout);
        aboutLayout.setHorizontalGroup(
            aboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        aboutLayout.setVerticalGroup(
            aboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        about.getAccessibleContext().setAccessibleDescription("");

        find.setTitle("Find");
        find.setBackground(new java.awt.Color(0, 153, 153));
        find.setMinimumSize(new java.awt.Dimension(500, 230));
        find.setResizable(false);

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.setToolTipText("Direction");

        jLabel9.setFont(new java.awt.Font("Centaur", 0, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 102));
        jLabel9.setText("Direction");
        jLabel9.setToolTipText("Direction");

        buttonGroup1.add(up);
        up.setFont(new java.awt.Font("Garamond", 1, 14)); // NOI18N
        up.setForeground(new java.awt.Color(102, 0, 0));
        up.setText("UP");
        up.setToolTipText("UP");

        buttonGroup1.add(down);
        down.setFont(new java.awt.Font("Garamond", 1, 14)); // NOI18N
        down.setForeground(new java.awt.Color(102, 0, 0));
        down.setText("Down");
        down.setToolTipText("Down");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(up)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addComponent(down)
                .addGap(24, 24, 24))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(up)
                    .addComponent(down))
                .addGap(0, 22, Short.MAX_VALUE))
        );

        matchCase.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        matchCase.setText("Match Case");
        matchCase.setToolTipText("Match Case");

        jLabel8.setFont(new java.awt.Font("Bell MT", 1, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 0, 0));
        jLabel8.setText("Find What");
        jLabel8.setToolTipText("Find What");

        findWhat.setFont(new java.awt.Font("Baskerville Old Face", 3, 14)); // NOI18N
        findWhat.setForeground(new java.awt.Color(0, 153, 153));
        findWhat.setToolTipText("Enter word To be Find");

        jButton2.setFont(new java.awt.Font("Baskerville Old Face", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 102, 102));
        jButton2.setText("Find Next");
        jButton2.setToolTipText("Find Next");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Baskerville Old Face", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 102, 102));
        jButton3.setText("Cancel");
        jButton3.setToolTipText("Cancel");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout findLayout = new javax.swing.GroupLayout(find.getContentPane());
        find.getContentPane().setLayout(findLayout);
        findLayout.setHorizontalGroup(
            findLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, findLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(findLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(findLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(57, 57, 57)
                        .addComponent(findWhat, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(25, Short.MAX_VALUE))
                    .addGroup(findLayout.createSequentialGroup()
                        .addComponent(matchCase, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61))))
            .addGroup(findLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(96, 96, 96))
        );
        findLayout.setVerticalGroup(
            findLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(findLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(findLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(findWhat, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(findLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addGroup(findLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(findLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(matchCase, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(findLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("JKNotepad");
        setMinimumSize(new java.awt.Dimension(600, 470));

        bottom.setBackground(new java.awt.Color(204, 255, 204));
        bottom.setToolTipText("Length and Line");

        details.setFont(new java.awt.Font("Bell MT", 0, 13)); // NOI18N
        details.setForeground(new java.awt.Color(0, 0, 51));
        details.setText("Length : 0 And Line : 0");
        details.setToolTipText("Lines and Text Numbers");

        javax.swing.GroupLayout bottomLayout = new javax.swing.GroupLayout(bottom);
        bottom.setLayout(bottomLayout);
        bottomLayout.setHorizontalGroup(
            bottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bottomLayout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(details, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(112, Short.MAX_VALUE))
        );
        bottomLayout.setVerticalGroup(
            bottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bottomLayout.createSequentialGroup()
                .addGap(0, 8, Short.MAX_VALUE)
                .addComponent(details))
        );

        wrar.setBackground(new java.awt.Color(102, 255, 204));
        wrar.setColumns(20);
        wrar.setRows(90);
        wrar.setTabSize(80);
        wrar.setToolTipText("Enter your Text");
        wrar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                wrarKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(wrar);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jMenuBar1.setToolTipText("Main Menu");

        file.setText("File");
        file.setToolTipText("File");
        file.addMenuKeyListener(new javax.swing.event.MenuKeyListener() {
            public void menuKeyPressed(javax.swing.event.MenuKeyEvent evt) {
                fileMenuKeyPressed(evt);
            }
            public void menuKeyReleased(javax.swing.event.MenuKeyEvent evt) {
            }
            public void menuKeyTyped(javax.swing.event.MenuKeyEvent evt) {
            }
        });
        file.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                fileMenuSelected(evt);
            }
        });
        file.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileActionPerformed(evt);
            }
        });

        newitem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        newitem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/new.png"))); // NOI18N
        newitem.setText("New...");
        newitem.setToolTipText("New...");
        newitem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newitemActionPerformed(evt);
            }
        });
        file.add(newitem);

        openitem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        openitem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/open.png"))); // NOI18N
        openitem.setText("Open....");
        openitem.setToolTipText("Open....");
        openitem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openitemActionPerformed(evt);
            }
        });
        file.add(openitem);

        saveitem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        saveitem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/save.png"))); // NOI18N
        saveitem.setText("Save...");
        saveitem.setToolTipText("Save...");
        saveitem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveitemActionPerformed(evt);
            }
        });
        file.add(saveitem);

        saveasitem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        saveasitem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/save.png"))); // NOI18N
        saveasitem.setText("Save As");
        saveasitem.setToolTipText("Save As");
        saveasitem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveasitemActionPerformed(evt);
            }
        });
        file.add(saveasitem);

        prntitem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        prntitem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/print.png"))); // NOI18N
        prntitem.setText("Print");
        prntitem.setToolTipText("Print");
        prntitem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prntitemActionPerformed(evt);
            }
        });
        file.add(prntitem);

        exititem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        exititem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/exit.png"))); // NOI18N
        exititem.setText("Exit");
        exititem.setToolTipText("Exit");
        exititem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exititemActionPerformed(evt);
            }
        });
        file.add(exititem);

        delitem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_MASK));
        delitem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/clear.png"))); // NOI18N
        delitem.setText("Delete...");
        delitem.setToolTipText("Delete...");
        delitem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delitemActionPerformed(evt);
            }
        });
        file.add(delitem);

        jMenuBar1.add(file);

        edit.setText("Edit");
        edit.setToolTipText("Edit");
        edit.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                editMenuSelected(evt);
            }
        });
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });

        cpyitem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_W, java.awt.event.InputEvent.CTRL_MASK));
        cpyitem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/copy.png"))); // NOI18N
        cpyitem.setText("Copy");
        cpyitem.setToolTipText("Copy");
        cpyitem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cpyitemActionPerformed(evt);
            }
        });
        edit.add(cpyitem);

        pstitem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_K, java.awt.event.InputEvent.CTRL_MASK));
        pstitem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/paste.png"))); // NOI18N
        pstitem.setText("Paste");
        pstitem.setToolTipText("Paste");
        pstitem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pstitemActionPerformed(evt);
            }
        });
        edit.add(pstitem);

        ctitm.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_MASK));
        ctitm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/cut.png"))); // NOI18N
        ctitm.setText("Cut");
        ctitm.setToolTipText("Cut");
        ctitm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ctitmActionPerformed(evt);
            }
        });
        edit.add(ctitm);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/attend.png"))); // NOI18N
        jMenuItem2.setText("Date and Time");
        jMenuItem2.setToolTipText("Date and Time");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        edit.add(jMenuItem2);

        jMenuBar1.add(edit);

        frmt.setText("Format");
        frmt.setToolTipText("Format");
        frmt.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                frmtMenuSelected(evt);
            }
        });
        frmt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                frmtActionPerformed(evt);
            }
        });

        fntclr.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        fntclr.setText("Change Font Colour");
        fntclr.setToolTipText("Change Font Colour");
        fntclr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fntclrActionPerformed(evt);
            }
        });
        frmt.add(fntclr);

        bgclr.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        bgclr.setText("Change Background Colour");
        bgclr.setToolTipText("Change Background Colour");
        bgclr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bgclrActionPerformed(evt);
            }
        });
        frmt.add(bgclr);

        fntstyl.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        fntstyl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/italic.png"))); // NOI18N
        fntstyl.setText("Font Style");
        fntstyl.setToolTipText("Font Style");
        fntstyl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fntstylActionPerformed(evt);
            }
        });
        frmt.add(fntstyl);

        fntfmly.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        fntfmly.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/bold.png"))); // NOI18N
        fntfmly.setText("Font Family");
        fntfmly.setToolTipText("Font Family");
        fntfmly.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fntfmlyActionPerformed(evt);
            }
        });
        frmt.add(fntfmly);

        fntsz.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Y, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        fntsz.setText("Font Size");
        fntsz.setToolTipText("Font Size");
        fntsz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fntszActionPerformed(evt);
            }
        });
        frmt.add(fntsz);

        fnd.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_MASK));
        fnd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/search.png"))); // NOI18N
        fnd.setText("Find");
        fnd.setToolTipText("Find");
        fnd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fndActionPerformed(evt);
            }
        });
        frmt.add(fnd);

        jMenuBar1.add(frmt);

        view.setText("View");
        view.setToolTipText("View");
        view.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                viewMenuSelected(evt);
            }
        });
        view.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewActionPerformed(evt);
            }
        });

        stbr.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        stbr.setSelected(true);
        stbr.setText("Status Bar");
        stbr.setToolTipText("Status Bar");
        stbr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stbrActionPerformed(evt);
            }
        });
        view.add(stbr);

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/about.png"))); // NOI18N
        jMenuItem1.setText("About Me");
        jMenuItem1.setToolTipText("About Me");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        view.add(jMenuItem1);

        jMenuBar1.add(view);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bottom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(bottom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exititemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exititemActionPerformed
        String strMsg="Do you Want To Save...??";
        String er="ALERT...!!";
        int len=wrar.getText().length();
//        System.out.println("Length :"+len);
        if(len>0){
            int x=JOptionPane.showConfirmDialog(null, strMsg, er, JOptionPane.YES_NO_OPTION);
//            System.out.println(x);
           if(x==JOptionPane.YES_OPTION){            
                try {
                    save();
                } catch (FileNotFoundException ex) {
                    String title = "Error";
                    String ms = "File  Not Saved....";
                    JOptionPane.showMessageDialog(null, ms, title, fstyle);
                    Logger.getLogger(ntpd.class.getName()).log(Level.SEVERE, null, ex);
                }
            }else if(x==JOptionPane.NO_OPTION){
                System.exit(0);
            }
        }else{
            dispose();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_exititemActionPerformed

    private void prntitemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prntitemActionPerformed
        JOptionPane.showMessageDialog(null,"\"Get ur printer repaired first...!! It seems u don't have one!\",\n" +"	\"Bad Printer\"");
        // TODO add your handling code here:
    }//GEN-LAST:event_prntitemActionPerformed
    public void newFile() throws IOException{
        String er="Error";
        String strMsg="Do You want to SaveChanges...??";
        if(wrar.getText().length() < 1){
            wrar.setText("");
            textChanged=false;
        }else{
            int x=JOptionPane.showConfirmDialog(null, strMsg, er, JOptionPane.YES_NO_OPTION);        
            if(x==JOptionPane.YES_OPTION){
               if("".equals(filename)){
                   saveAs();
               }else{
                   save();
               }
            }else{
                dispose();
                ntpd obj=new ntpd();
                obj.setVisible(true);
            }
        }
    }
    private void newitemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newitemActionPerformed
        try {
            newFile();
        } catch (Exception ex) {
            ex.printStackTrace();
            System.out.println(ex);
        }
    }//GEN-LAST:event_newitemActionPerformed

    private void openitemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openitemActionPerformed
        JFileChooser chooser=new JFileChooser();
        int chooserValue=chooser.showOpenDialog(this);
        if(chooserValue == JFileChooser.APPROVE_OPTION){
            try{
                Scanner fin=new Scanner(chooser.getSelectedFile());
                String buffer="";
                while(fin.hasNext()){
                    buffer += fin.nextLine() + "\n";
                }
                wrar.setText(buffer);                
            }catch(Exception e){
                JOptionPane.showMessageDialog(this, "File Not Found...!!");
            }
        }    
    }//GEN-LAST:event_openitemActionPerformed
    public void save() throws FileNotFoundException{
        JFileChooser chooser=new JFileChooser();
        int chooserValue=chooser.showSaveDialog(this);
        if(chooserValue == JFileChooser.APPROVE_OPTION){            
            PrintWriter fout=new PrintWriter(chooser.getSelectedFile());
            fout.print(wrar.getText());
            fout.close();                
        }
    }
    private void saveitemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveitemActionPerformed
        try {
            save();
            // TODO add your handling code here:
        } catch (FileNotFoundException ex) {
            Logger.getLogger(ntpd.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_saveitemActionPerformed
    public void saveAs() throws IOException{
        FileDialog fd=new FileDialog(ntpd.this,"save",FileDialog.SAVE);
        fd.show();
        if(fd.getFile() != null){
            fn=fd.getFile();
            dir=fd.getDirectory();
            filename=dir+fn+".txt";
            setTitle(filename);
            try{
                DataOutputStream d=new DataOutputStream(new FileOutputStream(filename));
                holdText=wrar.getText();
                BufferedReader br=new BufferedReader(new StringReader(holdText));
                while((holdText = br.readLine()) != null){
                    d.writeBytes(holdText + "\r\n");
                    d.close();                                    
                }
            }catch(Exception e){
                e.printStackTrace();
                System.out.println(e);
                JOptionPane.showMessageDialog(null, "An Error Has Been Occurred While Saving The File");
            }
        }
    }
    private void saveasitemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveasitemActionPerformed
        try {
            saveAs();
            // TODO add your handling code here:
        } catch (IOException ex) {
            Logger.getLogger(ntpd.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_saveasitemActionPerformed
    private void fntclrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fntclrActionPerformed
        Color c=JColorChooser.showDialog(this,"Choose Color",Color.BLACK);
        wrar.setForeground(c);                 
        // TODO add your handling code here:
    }//GEN-LAST:event_fntclrActionPerformed
    private void bgclrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bgclrActionPerformed
        Color c=JColorChooser.showDialog(this,"Choose Color",Color.BLACK);  
        wrar.setBackground(c);          
        // TODO add your handling code here:
    }//GEN-LAST:event_bgclrActionPerformed
    private void fntstylActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fntstylActionPerformed
        JOptionPane.showConfirmDialog(null, stylelist, "Choose Font Style", JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE);
        fstyle=stylevalue[stylelist.getSelectedIndex()];
        font1=new Font(ffamily,fstyle,fsize);
        wrar.setFont(font1);
        // TODO add your handling code here:
    }//GEN-LAST:event_fntstylActionPerformed
    private void fntfmlyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fntfmlyActionPerformed
        JOptionPane.showConfirmDialog(null, familylist, "Choose Font Family", JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE);
        ffamily=String.valueOf(familylist.getSelectedValue());
        font1=new Font(ffamily,fstyle,fsize);
        wrar.setFont(font1);
// TODO add your handling code here:
    }//GEN-LAST:event_fntfmlyActionPerformed
    private void fntszActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fntszActionPerformed
        JOptionPane.showConfirmDialog(null, sizelist, "Choose Font Size", JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE);
        fsizestr=String.valueOf(sizelist.getSelectedValue());
        fsize =Integer.parseInt(fsizestr);
        font1=new Font(ffamily,fstyle,fsize);
        wrar.setFont(font1);
        // TODO add your handling code here:
    }//GEN-LAST:event_fntszActionPerformed
    private void wrarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_wrarKeyTyped
        keyTyped(evt);
    }//GEN-LAST:event_wrarKeyTyped
    private void delitemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delitemActionPerformed
        JOptionPane.showMessageDialog(null, "Are You Sure .....???");
        dispose();        
        ntpd obj1=new ntpd();
        obj1.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_delitemActionPerformed
    private void pstitemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pstitemActionPerformed
        Transferable cliptran = clip.getContents(ntpd.this);
         try{
             String sel = (String) cliptran.getTransferData(DataFlavor.stringFlavor);
             wrar.replaceRange(sel,wrar.getSelectionStart(),wrar.getSelectionEnd());             
         }catch(UnsupportedFlavorException | IOException exc){
             System.out.println("not string flavour");
         }
        // TODO add your handling code here:
    }//GEN-LAST:event_pstitemActionPerformed
   
    public void copy(){        
        String sel = wrar.getSelectedText();
        System.out.println(sel);
        StringSelection clipString = new StringSelection(sel);
        clip.setContents(clipString,clipString);
        JOptionPane.showMessageDialog(null, "Text  Copied");
    }
    
    private void cpyitemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cpyitemActionPerformed
        copy();
        // TODO add your handling code here:
    }//GEN-LAST:event_cpyitemActionPerformed

    public void cut(){
        String sel = wrar.getSelectedText();        
        StringSelection ss = new StringSelection(sel);
        clip.setContents(ss,ss);
        wrar.replaceRange("",wrar.getSelectionStart(),wrar.getSelectionEnd());        
    }
    
    private void ctitmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ctitmActionPerformed
        cut();
        // TODO add your handling code here:
    }//GEN-LAST:event_ctitmActionPerformed

    private void stbrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stbrActionPerformed
        Boolean sl=null;
        sl=stbr.isSelected();
        System.out.println(sl);
        if(sl==true){
            bottom.setVisible(true);
        }else{
            bottom.setVisible(false);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_stbrActionPerformed
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        about.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        about.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        DateFormat df=new SimpleDateFormat("E yyyy/MM/dd HH:mm:ss");
        Date date=new Date();
        String sdt=df.format(date);
        System.out.println(sdt);
        wrar.append(sdt);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void fndActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fndActionPerformed
        find.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_fndActionPerformed
    
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        find.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    int findNext(){        
        String s1=wrar.getText();
        String s2=findWhat.getText();
        lastIndex=wrar.getCaretPosition();        
        int selStart=wrar.getSelectionStart();
        int selEnd=wrar.getSelectionEnd();       
        if(up.isSelected()){
            if(selStart!=selEnd)
                lastIndex=selEnd-s2.length()-1;
                if(!matchCase.isSelected())
                    lastIndex=s1.toUpperCase().lastIndexOf(s2.toUpperCase(),lastIndex);
                else
                    lastIndex=s1.lastIndexOf(s2,lastIndex);	
        }else{
            if(selStart!=selEnd)
                    lastIndex=selStart+1;
                    if(!matchCase.isSelected())
                        lastIndex=s1.toUpperCase().indexOf(s2.toUpperCase(),lastIndex);
                    else
                        lastIndex=s1.indexOf(s2,lastIndex);	
        }
        return lastIndex;
    }
    public void findNextWithSelection(){
        int idx=findNext();
        if(idx!=-1){
            wrar.setSelectionStart(idx);
            wrar.setSelectionEnd(idx+findWhat.getText().length());
        }else{
            JOptionPane.showMessageDialog(this,"Cannot find"+" \""+findWhat.getText()+"\"","Find",JOptionPane.INFORMATION_MESSAGE);
        }
   }
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        findNextWithSelection();        
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editActionPerformed

    private void fileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileActionPerformed
      // TODO add your handling code here:
    }//GEN-LAST:event_fileActionPerformed

    private void viewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_viewActionPerformed

    private void frmtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_frmtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_frmtActionPerformed

    private void fileMenuKeyPressed(javax.swing.event.MenuKeyEvent evt) {//GEN-FIRST:event_fileMenuKeyPressed
      // TODO add your handling code here:
    }//GEN-LAST:event_fileMenuKeyPressed

    private void fileMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_fileMenuSelected
        enabledisable();
        // TODO add your handling code here:
    }//GEN-LAST:event_fileMenuSelected

    private void editMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_editMenuSelected
        enabledisable();
        // TODO add your handling code here:
    }//GEN-LAST:event_editMenuSelected

    private void frmtMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_frmtMenuSelected
        enabledisable();
        // TODO add your handling code here:
    }//GEN-LAST:event_frmtMenuSelected

    private void viewMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_viewMenuSelected
        enabledisable();
        // TODO add your handling code here:
    }//GEN-LAST:event_viewMenuSelected

    public void keyTyped(KeyEvent ke){
        cl=wrar.getText().length();
        c2=cl+1;
	linecount=wrar.getLineCount();	
	details.setText("Length: "+c2+" And  Line: "+linecount);
    }		
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ntpd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new ntpd().setVisible(true);
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog about;
    private javax.swing.JMenuItem bgclr;
    javax.swing.JPanel bottom;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JMenuItem cpyitem;
    private javax.swing.JMenuItem ctitm;
    private javax.swing.JMenuItem delitem;
    javax.swing.JLabel details;
    private javax.swing.JRadioButton down;
    private javax.swing.JMenu edit;
    public javax.swing.JMenuItem exititem;
    public javax.swing.JMenu file;
    private javax.swing.JDialog find;
    private javax.swing.JTextField findWhat;
    private javax.swing.JMenuItem fnd;
    private javax.swing.JMenuItem fntclr;
    private javax.swing.JMenuItem fntfmly;
    private javax.swing.JMenuItem fntstyl;
    private javax.swing.JMenuItem fntsz;
    private javax.swing.JMenu frmt;
    private javax.swing.JLabel info;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JCheckBox matchCase;
    private javax.swing.JMenuItem newitem;
    private javax.swing.JMenuItem openitem;
    private javax.swing.JMenuItem prntitem;
    private javax.swing.JMenuItem pstitem;
    private javax.swing.JMenuItem saveasitem;
    public javax.swing.JMenuItem saveitem;
    private javax.swing.JRadioButtonMenuItem stbr;
    private javax.swing.JRadioButton up;
    private javax.swing.JMenu view;
    public javax.swing.JTextArea wrar;
    // End of variables declaration//GEN-END:variables
}
